### ISSUE TITLE
anchor-lang 0.24.2 is Incompatible with solana-rpc 1.9.13

### ISSUE THREAD

**Issue by ron-liu** [coral-xyz/anchor#1852]
When we upgrade to anchor-lang to 0.24.2 with solana-rpc `1.9.13`, it will complain the following issues. Anyone has idea?

```
Compiling solana-gossip v1.9.14
error[E0614]: type `u64` cannot be dereferenced
   --> /Users/rongliu/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-gossip-1.9.14/src/cluster_info_metrics.rs:574:35
    |
574 |         .map(|(slot, num_votes)| (*slot, *num_votes))
    |                                   ^^^^^

error[E0614]: type `usize` cannot be dereferenced
   --> /Users/rongliu/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-gossip-1.9.14/src/cluster_info_metrics.rs:574:42
    |
574 |         .map(|(slot, num_votes)| (*slot, *num_votes))
    |                                          ^^^^^^^^^^

error[E0614]: type `u64` cannot be dereferenced
   --> /Users/rongliu/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-gossip-1.9.14/src/cluster_info_metrics.rs:580:43
    |
580 |                 .map(|(slot, num_votes)| (*slot, *num_votes)),
    |                                           ^^^^^

error[E0614]: type `usize` cannot be dereferenced
   --> /Users/rongliu/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-gossip-1.9.14/src/cluster_info_metrics.rs:580:50
    |
580 |                 .map(|(slot, num_votes)| (*slot, *num_votes)),
```

**Comment by neery1218** [comment]
I ran into similar issues because I was using the nightly version of rust. what does:
`cargo --version`
and
'rustup show'
say?

If it says nightly is default, you can fix by doing `rustup default stable`
