### ISSUE TITLE
IDL: Types with generics are not assignable to parameter of type `Idl`

### ISSUE THREAD

**Issue by vadorovsky** [coral-xyz/anchor#2687]
When upgrading Light Protocol to Anchor 0.29, I encountered the following error, when using the `IDL` const as `Idl` type:

```
       src/multisigParams.ts(140,40): error TS2345: Argument of type 'Multisig' is not assignable to parameter of type 'Idl'.
         Types of property 'accounts' are incompatible.
           Type '[{ name: "eventMerkleTree"; type: { kind: "struct"; fields: [{ name: "merkleTreeNr"; type: "u64"; }, { name: "newest"; type: "u8"; }, { name: "padding"; type: { array: ["u8", 7]; }; }, { name: "merkleTree"; type: { ...; }; }]; }; }, { ...; }, { ...; }]' is not assignable to type 'IdlAccountDef[]'.
             Type '{ name: "eventMerkleTree"; type: { kind: "struct"; fields: [{ name: "merkleTreeNr"; type: "u64"; }, { name: "newest"; type: "u8"; }, { name: "padding"; type: { array: ["u8", 7]; }; }, { name: "merkleTree"; type: { ...; }; }]; }; } | { ...; } | { ...; }' is not assignable to type 'IdlAccountDef'.
               Type '{ name: "eventMerkleTree"; type: { kind: "struct"; fields: [{ name: "merkleTreeNr"; type: "u64"; }, { name: "newest"; type: "u8"; }, { name: "padding"; type: { array: ["u8", 7]; }; }, { name: "merkleTree"; type: { ...; }; }]; }; }' is not assignable to type 'IdlAccountDef'.
                 The types of 'type.fields' are incompatible between these types.
                   Type '[{ name: "merkleTreeNr"; type: "u64"; }, { name: "newest"; type: "u8"; }, { name: "padding"; type: { array: ["u8", 7]; }; }, { name: "merkleTree"; type: { definedWithTypeArgs: { name: "MerkleTreeSha256"; args: [...]; }; }; }]' is not assignable to type 'IdlTypeDefStruct'.
                     Type '{ name: "merkleTreeNr"; type: "u64"; } | { name: "newest"; type: "u8"; } | { name: "padding"; type: { array: ["u8", 7]; }; } | { name: "merkleTree"; type: { definedWithTypeArgs: { name: "MerkleTreeSha256"; args: [...]; }; }; }' is not assignable to type 'IdlField'.
                       Type '{ name: "merkleTree"; type: { definedWithTypeArgs: { name: "MerkleTreeSha256"; args: [{ value: "18"; }, { value: "20"; }]; }; }; }' is not assignable to type 'IdlField'.
                         Types of property 'type' are incompatible.
                           Type '{ definedWithTypeArgs: { name: "MerkleTreeSha256"; args: [{ value: "18"; }, { value: "20"; }]; }; }' is not assignable to type 'IdlType'.
       src/multisigParams.ts(145,40): error TS2345: Argument of type 'Multisig' is not assignable to parameter of type 'Idl'.
       src/transaction.ts(35,42): error TS2345: Argument of type 'Multisig' is not assignable to parameter of type 'Idl'.
       src/transaction.ts(40,42): error TS2345: Argument of type 'Multisig' is not assignable to parameter of type 'Idl'.
       src/client.ts(51,21): error TS2344: Type 'Multisig' does not satisfy the constraint 'Idl'.
       src/client.ts(77,5): error TS2322: Type 'Program<Idl>' is not assignable to type 'Program<Multisig>'.
         Types of property 'account' are incompatible.
           Type 'AccountNamespace<Idl>' is missing the following properties from type 'AccountNamespace<Multisig>': transactionMerkleTree, eventMerkleTree, verifierState10Ins
       src/client.ts(77,33): error TS2345: Argument of type 'Multisig' is not assignable to parameter of type 'Idl'.
       src/client.ts(212,9): error TS2322: Type 'Multisig' is not assignable to type 'Idl'.
         Types of property 'accounts' are incompatible.
           Type '[{ name: "eventMerkleTree"; type: { kind: "struct"; fields: [{ name: "merkleTreeNr"; type: "u64"; }, { name: "newest"; type: "u8"; }, { name: "padding"; type: { array: ["u8", 7]; }; }, { name: "merkleTree"; type: { ...; }; }]; }; }, { ...; }, { ...; }]' is not assignable to type 'IdlAccountDef[]'.
             Type '{ name: "eventMerkleTree"; type: { kind: "struct"; fields: [{ name: "merkleTreeNr"; type: "u64"; }, { name: "newest"; type: "u8"; }, { name: "padding"; type: { array: ["u8", 7]; }; }, { name: "merkleTree"; type: { ...; }; }]; }; } | { ...; } | { ...; }' is not assignable to type 'IdlAccountDef'.
               Type '{ name: "eventMerkleTree"; type: { kind: "struct"; fields: [{ name: "merkleTreeNr"; type: "u64"; }, { name: "newest"; type: "u8"; }, { name: "padding"; type: { array: ["u8", 7]; }; }, { name: "merkleTree"; type: { ...; }; }]; }; }' is not assignable to type 'IdlAccountDef'.
                 The types of 'type.fields' are incompatible between these types.
                   Type '[{ name: "merkleTreeNr"; type: "u64"; }, { name: "newest"; type: "u8"; }, { name: "padding"; type: { array: ["u8", 7]; }; }, { name: "merkleTree"; type: { definedWithTypeArgs: { name: "MerkleTreeSha256"; args: [...]; }; }; }]' is not assignable to type 'IdlTypeDefStruct'.
                     Type '{ name: "merkleTreeNr"; type: "u64"; } | { name: "newest"; type: "u8"; } | { name: "padding"; type: { array: ["u8", 7]; }; } | { name: "merkleTree"; type: { definedWithTypeArgs: { name: "MerkleTreeSha256"; args: [...]; }; }; }' is not assignable to type 'IdlField'.
                       Type '{ name: "merkleTree"; type: { definedWithTypeArgs: { name: "MerkleTreeSha256"; args: [{ value: "18"; }, { value: "20"; }]; }; }; }' is not assignable to type 'IdlField'.
                         Types of property 'type' are incompatible.
                           Type '{ definedWithTypeArgs: { name: "MerkleTreeSha256"; args: [{ value: "18"; }, { value: "20"; }]; }; }' is not assignable to type 'IdlType'.
       src/client.ts(223,9): error TS2322: Type 'Multisig' is not assignable to type 'Idl'.
       src/multisig.ts(65,50): error TS2345: Argument of type 'Multisig' is not assignable to parameter of type 'Idl'.
        ELIFECYCLE  Command failed with exit code 1.
```

The reason is that the following IDL types from Rust, introduced in #2011:

https://github.com/coral-xyz/anchor/blob/7e5bdce710f9580e1489089d04afb13f71a5d1c7/lang/syn/src/idl/types.rs#L210-L215

are missing in `ts/packages/anchor/src/idl.ts`

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/2824.
